# wget -O "output-global/GlobalEndpoints/Ajax.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Ajax&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/Database.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Database&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/FTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=FTP&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/File.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=File&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/Generic.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Generic&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/HTTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=HTTP&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/IMAP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=IMAP&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/JMS.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=JMS&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/Jetty.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Jetty&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/POP3.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=POP3&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/Quartz.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Quartz&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/RMI.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=RMI&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/SAP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SAP&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/SFTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SFTP&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/SMTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SMTP&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/SSL(TLS).html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SSL(TLS)&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/Servlet.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Servlet&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/TCP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=TCP&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/UDP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=UDP&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/VM.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=VM&global=y&connectors="
# wget -O "output-global/GlobalEndpoints/WMQ.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=WMQ&global=y&connectors="


wget -O "output-global/GlobalConnectors/Ajax.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Ajax&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/Database.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Database&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/FTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=FTP&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/File.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=File&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/Generic.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Generic&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/HTTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=HTTP&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/IMAP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=IMAP&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/JMS.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=JMS&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/Jetty.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Jetty&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/POP3.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=POP3&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/Quartz.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Quartz&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/RMI.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=RMI&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/SAP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SAP&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/SFTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SFTP&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/SMTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SMTP&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/SSL(TLS).html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SSL(TLS)&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/Servlet.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Servlet&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/TCP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=TCP&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/UDP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=UDP&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/VM.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=VM&global=y&connectors=y"
wget -O "output-global/GlobalConnectors/WMQ.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=WMQ&global=y&connectors=y"
