wget -O "output/Endpoints/Ajax.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Ajax&global=$1"
wget -O "output/Endpoints/Database.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Database&global=$1"
wget -O "output/Endpoints/FTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=FTP&global=$1"
wget -O "output/Endpoints/File.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=File&global=$1"
wget -O "output/Endpoints/Generic.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Generic&global=$1"
wget -O "output/Endpoints/HTTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=HTTP&global=$1"
wget -O "output/Endpoints/IMAP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=IMAP&global=$1"
wget -O "output/Endpoints/JMS.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=JMS&global=$1"
wget -O "output/Endpoints/Jetty.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Jetty&global=$1"
wget -O "output/Endpoints/POP3.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=POP3&global=$1"
wget -O "output/Endpoints/Quartz.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Quartz&global=$1"
wget -O "output/Endpoints/RMI.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=RMI&global=$1"
wget -O "output/Endpoints/SAP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SAP&global=$1"
wget -O "output/Endpoints/SFTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SFTP&global=$1"
wget -O "output/Endpoints/SMTP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SMTP&global=$1"
wget -O "output/Endpoints/SSL(TLS).html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=SSL(TLS)&global=$1"
wget -O "output/Endpoints/Servlet.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=Servlet&global=$1"
wget -O "output/Endpoints/TCP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=TCP&global=$1"
wget -O "output/Endpoints/UDP.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=UDP&global=$1"
wget -O "output/Endpoints/VM.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=VM&global=$1"
wget -O "output/Endpoints/WMQ.html" "http://localhost/helpgen/page.php?Palette_Type=Endpoints&Palette_Item=WMQ&global=$1"
wget -O "output/Scopes/Async.html" "http://localhost/helpgen/page.php?Palette_Type=Scopes&Palette_Item=Async&global=$1"
wget -O "output/Scopes/Cache.html" "http://localhost/helpgen/page.php?Palette_Type=Scopes&Palette_Item=Cache&global=$1"
wget -O "output/Scopes/Composite Source.html" "http://localhost/helpgen/page.php?Palette_Type=Scopes&Palette_Item=Composite%20Source&global=$1"
wget -O "output/Scopes/Flow.html" "http://localhost/helpgen/page.php?Palette_Type=Scopes&Palette_Item=Flow&global=$1"
wget -O "output/Scopes/For Each.html" "http://localhost/helpgen/page.php?Palette_Type=Scopes&Palette_Item=For%20Each&global=$1"
wget -O "output/Scopes/Message Enricher.html" "http://localhost/helpgen/page.php?Palette_Type=Scopes&Palette_Item=Message%20Enricher&global=$1"
wget -O "output/Scopes/Poll.html" "http://localhost/helpgen/page.php?Palette_Type=Scopes&Palette_Item=Poll&global=$1"
wget -O "output/Scopes/Sub Flow.html" "http://localhost/helpgen/page.php?Palette_Type=Scopes&Palette_Item=Sub%20Flow&global=$1"
wget -O "output/Scopes/Until Successful.html" "http://localhost/helpgen/page.php?Palette_Type=Scopes&Palette_Item=Until%20Successful&global=$1"
wget -O "output/Components/Echo.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Echo&global=$1"
wget -O "output/Components/Expression.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Expression&global=$1"
wget -O "output/Components/Flow Reference.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Flow%20Reference&global=$1"
wget -O "output/Components/Groovy.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Groovy&global=$1"
wget -O "output/Components/HTTP Response Builder.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=HTTP%20Response%20Builder&global=$1"
wget -O "output/Components/Java.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Java&global=$1"
wget -O "output/Components/Javascript.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Javascript&global=$1"
wget -O "output/Components/Logger.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Logger&global=$1"
wget -O "output/Components/Python.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Python&global=$1"
wget -O "output/Components/REST.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=REST&global=$1"
wget -O "output/Components/Ruby.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Ruby&global=$1"
wget -O "output/Components/SOAP.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=SOAP&global=$1"
wget -O "output/Components/Script.html" "http://localhost/helpgen/page.php?Palette_Type=Components&Palette_Item=Script&global=$1"
wget -O "output/Transformers/Append String.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Append%20String&global=$1"
wget -O "output/Transformers/Attachment.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Attachment&global=$1"
wget -O "output/Transformers/Body to Parameter Map.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Body%20to%20Parameter%20Map&global=$1"
wget -O "output/Transformers/Byte Array to MIME.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Byte%20Array%20to%20MIME&global=$1"
wget -O "output/Transformers/Byte Array to Object.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Byte%20Array%20to%20Object&global=$1"
wget -O "output/Transformers/Byte Array to Serializable.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Byte%20Array%20to%20Serializable&global=$1"
wget -O "output/Transformers/Byte Array to String.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Byte%20Array%20to%20String&global=$1"
wget -O "output/Transformers/CSV to Maps.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=CSV%20to%20Maps&global=$1"
wget -O "output/Transformers/DataMapper.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=DataMapper&global=$1"
wget -O "output/Transformers/Email to String.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Email%20to%20String&global=$1"
wget -O "output/Transformers/Expression.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Expression&global=$1"
wget -O "output/Transformers/File to Byte Array.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=File%20to%20Byte%20Array&global=$1"
wget -O "output/Transformers/File to String.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=File%20to%20String&global=$1"
wget -O "output/Transformers/Groovy.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Groovy&global=$1"
wget -O "output/Transformers/HTTP Response to Object.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=HTTP%20Response%20to%20Object&global=$1"
wget -O "output/Transformers/HTTP Response to String.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=HTTP%20Response%20to%20String&global=$1"
wget -O "output/Transformers/JSON to Object.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=JSON%20to%20Object&global=$1"
wget -O "output/Transformers/Java.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Java&global=$1"
wget -O "output/Transformers/Javascript.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Javascript&global=$1"
wget -O "output/Transformers/JMSMessage to Object.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=JMSMessage%20to%20Object&global=$1"
wget -O "output/Transformers/MIME to Byte Array.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=MIME%20to%20Byte%20Array&global=$1"
wget -O "output/Transformers/Maps to CSV.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Maps%20to%20CSV&global=$1"
wget -O "output/Transformers/Maps to XML.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Maps%20to%20XML&global=$1"
wget -O "output/Transformers/Message Properties.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Message%20Properties&global=$1"
wget -O "output/Transformers/Message to HTTP Response.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Message%20to%20HTTP%20Response&global=$1"
wget -O "output/Transformers/Message to Object.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Message%20to%20Object&global=$1"
wget -O "output/Transformers/MongoDB.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=MongoDB&global=$1"
wget -O "output/Transformers/Object to Byte Array.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Object%20to%20Byte%20Array&global=$1"
wget -O "output/Transformers/Object to HTTP Request.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Object%20to%20HTTP%20Request&global=$1"
wget -O "output/Transformers/Object to JSON.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Object%20to%20JSON&global=$1"
wget -O "output/Transformers/Object to JMSMessage.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Object%20to%20JMSMessage&global=$1"
wget -O "output/Transformers/Object to MIME.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Object%20to%20MIME&global=$1"
wget -O "output/Transformers/Object to Message.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Object%20to%20Message&global=$1"
wget -O "output/Transformers/Object to String.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Object%20to%20String&global=$1"
wget -O "output/Transformers/Object to XML.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Object%20to%20XML&global=$1"
wget -O "output/Transformers/Parse Template.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Parse%20Template&global=$1"
wget -O "output/Transformers/Property.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Property&global=$1"
wget -O "output/Transformers/Python.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Python&global=$1"
wget -O "output/Transformers/Resultset to Maps.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Resultset%20to%20Maps&global=$1"
wget -O "output/Transformers/Ruby.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Ruby&global=$1"
wget -O "output/Transformers/SAP Object to XML.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=SAP%20Object%20to%20XML&global=$1"
wget -O "output/Transformers/Script.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Script&global=$1"
wget -O "output/Transformers/Serializable to Byte Array.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Serializable%20to%20Byte%20Array&global=$1"
wget -O "output/Transformers/Session Variable.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Session%20Variable&global=$1"
wget -O "output/Transformers/Set Payload.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Set%20Payload&global=$1"
wget -O "output/Transformers/String to Byte Array.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=String%20to%20Byte%20Array&global=$1"
wget -O "output/Transformers/String to Email.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=String%20to%20Email&global=$1"
wget -O "output/Transformers/Transformer Reference.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Transformer%20Reference&global=$1"
wget -O "output/Transformers/Variable.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=Variable&global=$1"
wget -O "output/Transformers/XML to Maps.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=XML%20to%20Maps&global=$1"
wget -O "output/Transformers/XML to Object.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=XML%20to%20Object&global=$1"
wget -O "output/Transformers/XML to SAP Function (BAPI).html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=XML%20to%20SAP%20Function%20(BAPI)&global=$1"
wget -O "output/Transformers/XML to SAP IDoc.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=XML%20to%20SAP%20IDoc&global=$1"
wget -O "output/Transformers/XSLT.html" "http://localhost/helpgen/page.php?Palette_Type=Transformers&Palette_Item=XSLT&global=$1"
wget -O "output/Filters/And.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=And&global=$1"
wget -O "output/Filters/Custom.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Custom&global=$1"
wget -O "output/Filters/Exception.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Exception&global=$1"
wget -O "output/Filters/Expression.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Expression&global=$1"
wget -O "output/Filters/Filter Reference.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Filter%20Reference&global=$1"
wget -O "output/Filters/Idempotent Message.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Idempotent%20Message&global=$1"
wget -O "output/Filters/Message.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Message&global=$1"
wget -O "output/Filters/Message Property.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Message%20Property&global=$1"
wget -O "output/Filters/Not.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Not&global=$1"
wget -O "output/Filters/Or.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Or&global=$1"
wget -O "output/Filters/Payload.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Payload&global=$1"
wget -O "output/Filters/Regex.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Regex&global=$1"
wget -O "output/Filters/Schema Validation.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Schema%20Validation&global=$1"
wget -O "output/Filters/Wildcard.html" "http://localhost/helpgen/page.php?Palette_Type=Filters&Palette_Item=Wildcard&global=$1"
wget -O "output/Flow Control/All.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=All&global=$1"
wget -O "output/Flow Control/Choice.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=Choice&global=$1"
wget -O "output/Flow Control/Collection Aggregator.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=Collection%20Aggregator&global=$1"
wget -O "output/Flow Control/Collection Splitter.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=Collection%20Splitter&global=$1"
wget -O "output/Flow Control/Custom Aggregator.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=Custom%20Aggregator&global=$1"
wget -O "output/Flow Control/First Successful.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=First%20Successful&global=$1"
wget -O "output/Flow Control/Message Chunk Aggregator.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=Message%20Chunk%20Aggregator&global=$1"
wget -O "output/Flow Control/Message Chunk Splitter.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=Message%20Chunk%20Splitter&global=$1"
wget -O "output/Flow Control/Resequencer.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=Resequencer&global=$1"
wget -O "output/Flow Control/Round Robin.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=Round%20Robin&global=$1"
wget -O "output/Flow Control/Splitter.html" "http://localhost/helpgen/page.php?Palette_Type=Flow%20Control&Palette_Item=Splitter&global=$1"
wget -O "output/Error Handling/Catch Exception Strategy.html" "http://localhost/helpgen/page.php?Palette_Type=Error%20Handling&Palette_Item=Catch%20Exception%20Strategy&global=$1"
wget -O "output/Error Handling/Choice Exception Strategy.html" "http://localhost/helpgen/page.php?Palette_Type=Error%20Handling&Palette_Item=Choice%20Exception%20Strategy&global=$1"
wget -O "output/Error Handling/Reference Exception Strategy.html" "http://localhost/helpgen/page.php?Palette_Type=Error%20Handling&Palette_Item=Reference%20Exception%20Strategy&global=$1"
wget -O "output/Error Handling/Rollback Exception Strategy.html" "http://localhost/helpgen/page.php?Palette_Type=Error%20Handling&Palette_Item=Rollback%20Exception%20Strategy&global=$1"
wget -O "output/Cloud Connectors/CMIS.html" "http://localhost/helpgen/page.php?Palette_Type=Cloud%20Connectors&Palette_Item=CMIS&global=$1"
wget -O "output/Cloud Connectors/Magento.html" "http://localhost/helpgen/page.php?Palette_Type=Cloud%20Connectors&Palette_Item=Magento&global=$1"
wget -O "output/Cloud Connectors/MongoDB.html" "http://localhost/helpgen/page.php?Palette_Type=Cloud%20Connectors&Palette_Item=MongoDB&global=$1"
wget -O "output/Cloud Connectors/Salesforce.html" "http://localhost/helpgen/page.php?Palette_Type=Cloud%20Connectors&Palette_Item=Salesforce&global=$1"
wget -O "output/Cloud Connectors/Twilio.html" "http://localhost/helpgen/page.php?Palette_Type=Cloud%20Connectors&Palette_Item=Twilio&global=$1"
wget -O "output/Cloud Connectors/Twitter.html" "http://localhost/helpgen/page.php?Palette_Type=Cloud%20Connectors&Palette_Item=Twitter&global=$1"
wget -O "output/Other/Custom Business event.html" "http://localhost/helpgen/page.php?Palette_Type=Other&Palette_Item=Custom%20Business%20event&global=$1"
